### ISSUE TITLE
Error: The code generator has deoptimised the styling...

### ISSUE THREAD

**Issue by benjastraub** [mathisonian/dimensionality-reduction#5]
Hi, I just downloaded the project, but I'm having trouble running it.

I ran `npm install` and fixed the vulnerabilities, but when I use `idyll` to run it, it displays the following:

```
Building Idyll project with output directory: build

[BABEL] Note: The code generator has deoptimised the styling of "/Users/benjastraubMB/Documents/dimensionality-reduction-master/.idyll/_stream_3.js" as it exceeds the max of "500KB".
[Idyll] Access URLs:
 ----------------------------------
    Local: http://localhost:3000
 External: http://192.168.0.14:3000
 ----------------------------------
[Idyll] Serving files from: /Users/benjastraubMB/Documents/dimensionality-reduction-master/build
```

and it looks like this in the browser:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/30667727/46838250-cf31d600-cd8e-11e8-9ea4-c2991f6ff956.png">

**Comment by mathisonian** [comment]
Hey @benjastraub,

Are there errors in the JavaScript console? What version of Idyll do you have installed?

**Comment by benjastraub** [comment]
@mathisonian 

That's all in the mac terminal. I ran `npm update` just before compiling so it is on version 3.8.5

**Comment by mathisonian** [comment]
I found the issue - our custom _index.html template needed to be upgraded to work with the latest version of idyll. I've pushed this change so things should work as expected now.

Note you'll still see that de-optimized styling warning, that's a separate issue.
